services:  
  lancamentos-api:
    container_name: lancamentos-api
    depends_on:
      - rabbitmq
    build:
      context: ../
      dockerfile: ./src/FC.Lancamentos.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  consolidado-api:
    container_name: consolidado-api
    depends_on:
      - consolidado-db
      - rabbitmq
      - redis
    build:
      context: ../
      dockerfile: ./src/FC.Consolidado.Api/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  consolidado-db:
    image: postgres:latest
    container_name: consolidado-db
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: developer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: developer
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data: